### ISSUE TITLE
Disable uses-material-design: true

### ISSUE THREAD

**Issue by rienkkk** [Milad-Akarie/skeletonizer#11]
I don't use material design in my app, and get the following warning from skeletonizer. (It does not effect the app in any other way)

```
package:skeletonizer has `uses-material-design: true` set but the primary pubspec contains `uses-material-design: false`. If the application needs material icons, then `uses-material-design`  must be set to true.
```

Is it necessary for the skeletonizer to use material design or can it be disabled?

**Comment by Milad-Akarie** [comment]
Hey @rienkkk it can be disabled but right now I'm using it in tests ( testing icon skeletonization ) I'll try to figure out a way to use it in tests only if not I'm disabling it anyways.

**Comment by Milad-Akarie** [comment]
Hey @rienkkk  turns out some testing library I'm using has uses-material-design set to true so I can't just remove it, I'm closing this for now.
