### ISSUE TITLE
Icons shimmer boxes is missplaced to the bottom a bit

### ISSUE THREAD

**Issue by mohn93** [Milad-Akarie/skeletonizer#12]
First of all thanks for this great package I think it will have great potential

Please take a look at this

![Screenshot 2023-09-07 at 1 21 47 PM](https://github.com/Milad-Akarie/skeletonizer/assets/11969733/a2f3697d-5e1e-474d-9624-9f777e3faedd)

**Comment by Milad-Akarie** [comment]
@mohn93 I'm gonna need more info on how to reproduce this, I've tested with flutter's material icons and they seem to work fine, are you maybe using an old flutter version?

**Comment by mohn93** [comment]
@Milad-Akarie After checking it doesn't happen with flutter icons, it happens with icons generated with icon_font_generator

**Comment by Gagaved** [comment]
"It's true, I've encountered the same issue. We're also generating icons using icon_font_generator."

**Comment by Milad-Akarie** [comment]
@mohn93 @Gagaved the cause of that was a mistype alignment in the old versions 
of icon_font_generator package, I don't see any issues with the current update 4.0.0.

feel free to reopen if that's not the case.
