### ISSUE TITLE
Color of Skeleton

### ISSUE THREAD

**Issue by germes96** [Milad-Akarie/skeletonizer#18]
Wen i define The skeleton like this: 

 Skeletonizer(
      containersColor: Theme.of(context).colorScheme.surface,
      ....)

is it possible to define the color of the skeleton?
In order to well manage dark mode.

Thanks

**Comment by anlumo** [comment]
Yes: https://pub.dev/documentation/skeletonizer/latest/skeletonizer/ShimmerEffect/ShimmerEffect.html

It's the `baseColor` and `hightlightColor`. Pass that object to the `effect` parameter of `Skeletonizer`.

**Comment by germes96** [comment]
Thanks, I will!

Le mar. 7 nov. 2023 à 18:10, Andreas Monitzer ***@***.***> a
écrit :
