### ISSUE TITLE
Not work properly in RTL 

### ISSUE THREAD

**Issue by moyasser-hazim** [Milad-Akarie/skeletonizer#19]
When changing direction to RTL the skeleton hides, 
I faced this issue when upgrading the Flutter SDK to 3.16.2

**Comment by Milad-Akarie** [comment]
Hey @moyasser-hazim in general RTL is working just fine, would you share the code snippet that didn't work for you?

**Comment by moyasser-hazim** [comment]
Hey @Milad-Akarie 
It works properly but when I upgrade Flutter SDK to 3.16.0 the RTL does not work fine, you can check your example also doesn't work fine when upgrading Flutter SDK.

**Comment by Milad-Akarie** [comment]
@moyasser-hazim seems like everything is fine
![image](https://github.com/Milad-Akarie/skeletonizer/assets/55059449/ebc9d1a1-10fd-48a6-bcd7-30817068cc6b)
care to share some recordings of what's going on wrong with your setup?

**Comment by moyasser-hazim** [comment]
After upgrading the package to 0.9.0 it works properly, Thanks for fixing the package issue so quickly! Appreciate it!
