### ISSUE TITLE
Can't skeletonize svg widget

### ISSUE THREAD

**Issue by 3kdeveloper** [Milad-Akarie/skeletonizer#21]
![Simulator Screen Shot - iPhone 14 Pro - 2024-01-05 at 19 18 48](https://github.com/Milad-Akarie/skeletonizer/assets/77343380/e48bcf85-c3b5-4781-8859-8d4a7472ab7d)

**Comment by 3kdeveloper** [comment]
SvgPicture.asset(
AppImages.callIcon,
width: 30,
height: 30,
 ),

**Comment by divyeshgohil85** [comment]
@3kdeveloper Hello, How did you solved this?

**Comment by KetanSatani-TheOneTech** [comment]
@3kdeveloper Not sure why did you closed this issue. It's still there.

`SvgPicture.network(model.image ?? '')`

If we take this it's not working.

**Comment by 3kdeveloper** [comment]
@KetanSatani-TheOneTech  Check out the solution 

`  Widget applyShimmer({
    double? width = double.maxFinite,
    double? height,
    BorderRadius? borderRadius,
  }) =>
      Skeleton.replace(
        replacement: Container(
          width: width,
          height: height,
          decoration: BoxDecoration(
              borderRadius: borderRadius, color: Colors.transparent),
          child: const ColoredBox(color: Colors.black),
        ),
        child: this,
      );`

add this inside your widget extension.

**Comment by seragsabrysakr** [comment]
could you give an example to how to add apply shimmer

**Comment by 3kdeveloper** [comment]
@seragsabrysakr 

YourWidget( ... ).applyShimmer(width: 40.w, height: 40.h)
