### ISSUE TITLE
Animations when content loading has finished

### ISSUE THREAD

**Issue by client-side96** [Milad-Akarie/skeletonizer#22]
First of all thanks for this great library that enabled us to implement skeletons in our flutter app very quickly. 🚀 

I wondered if there is a possibility to apply a FadeIn animation when the content is loaded. So when the skeleton disappear, the real data could be animated to have a nicer transition. 

What I tried so far is wrapping the child of the `Skeletonizer` in a `AnimationSwitcher` widget, but I guess that does not work, as the child widget is not replaced by the skeleton but rather the contents are replaced by it.

**Comment by coolswood** [comment]
@Milad-Akarie Hey! Thank you for you lib!
Is there any chance that this feature will be implemented? It seems to be quite important for user experience

**Comment by Milad-Akarie** [comment]
It's planned yes

**Comment by Milad-Akarie** [comment]
@client-side96 switch animation was added to skeletonizer 1.3.0
