### ISSUE TITLE
Animation to ListViewBuilder items effects as they are one piece

### ISSUE THREAD

**Issue by mNouh94** [Milad-Akarie/skeletonizer#28]
Hello,

When i use ListViewBuilder the animation effected to the items looks like they are one item and not each item separated by it's self, how may i apply the effect the animation for each item.

![Screenshot 2024-03-24 at 4 55 17 PM](https://github.com/Milad-Akarie/skeletonizer/assets/47349530/a699a73e-018b-489c-a57a-a899d48fcd81)

Here's the code

`  @override
  Widget build(BuildContext context) {
    return Skeletonizer(
      enabled: _isEnabled,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 20),
        child: healthcareProviders.isNotEmpty
            ? ListView.separated(
                shrinkWrap: true,
                itemCount: healthcareProviders.length,
                physics: const NeverScrollableScrollPhysics(),
                itemBuilder: (context, index) => HealthcareProviderItem(
                  healthcareProvider: healthcareProviders[index],
                ),
                separatorBuilder: (context, index) =>
                    const SizedBox(height: 15),
              )
            : NoDataWidget(
                isCentered: true,
                svgIcon: AppSvgs.news,
                text: context.localizations.noHealthcareProviders,
              ),
      ),
    );
  }`
  
  and this is the item code
  
  `  @override
  Widget build(BuildContext context) {
    return InkWell(
      splashColor: Colors.transparent,
      highlightColor: Colors.transparent,
      onTap: () => context.router.push(
        AppRoutes.healthcareProviderDetailsRoute,
        extra: healthcareProvider,
      ),
      child: Skeleton.unite(
        child: SizedBox(
          height: 200,
          child: Stack(
            children: [
              HealthcareProviderImage(imageUrl: healthcareProvider.image),
              Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(15),
                  gradient: AppColors.imageGradientBlue,
                ),
              ),
              Positioned(
                bottom: 7,
                left: 14,
                right: 15,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      healthcareProvider.name,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style:
                          AppStyles.sectionTitle.copyWith(color: Colors.white),
                    ),
                    const SizedBox(height: 5),
                    Text(
                      healthcareProvider.description,
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                      style: AppStyles.description.copyWith(
                        color: Colors.white,
                        height: 1.1,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }`

**Comment by Milad-Akarie** [comment]
@mNouh94 Thats the intended/recommended behavior, if you want to skeletonize every item then wrap every item with a Skeletonizer

**Comment by mNouh94** [comment]
@Milad-Akarie When the items are big the behavior will not look good as i showed, i wrapped the items and it's works fine, Thank you

![Uploading Screenshot 2024-03-27 at 3.20.54 PM.png…]()
