### ISSUE TITLE
Skeleton.leaf has no effect

### ISSUE THREAD

**Issue by ripls56** [Milad-Akarie/skeletonizer#30]
[Provided example](https://pub.dev/packages/skeletonizer#skeletonleaf) has no any effect.

```dart
return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Skeletonizer(
          child: Skeleton.leaf(
            child: Card(
              child: ListTile(
                title: Text('The title goes here'),
                subtitle: Text('Subtitle here'),
                trailing: Icon(Icons.ac_unit, size: 40),
              ),
            ),
          ),
        ),
      ),
    );
```

above code result:
![result](https://github.com/Milad-Akarie/skeletonizer/assets/84716344/72741b78-efb1-4413-bcfb-b7e5b86e547f)

flutter doctor:
[✓] Flutter (Channel beta, 3.21.0-1.0.pre.2, on macOS 14.4 23E214 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 15.2)
    ✗ Unable to get list of installed Simulator runtimes.
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.4)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources

**Comment by Milad-Akarie** [comment]
@ripls56 This works fine on the latest stable version of Flutter, might this be caused by some change in the beta channel? can you check if the issue exists in on the stable channel?

**Comment by ripls56** [comment]
> @ripls56 This works fine on the latest stable version of Flutter, might this be caused by some change in the beta channel? can you check if the issue exists in on the stable channel?

Also tried disable impeller, same thing:
![result-stable](https://github.com/Milad-Akarie/skeletonizer/assets/84716344/34a832ca-6a63-4365-8341-c56f67788cc4)

full code (if needed):
```
import 'package:flutter/material.dart';
import 'package:skeletonizer/skeletonizer.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.red,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Skeletonizer(
          enabled: true,
          child: Skeleton.leaf(
            child: Card(
              child: ListTile(
                title: Text('The title goes here'),
                subtitle: Text('Subtitle here'),
                trailing: Icon(Icons.ac_unit, size: 40),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by ripls56** [comment]
Ok its probably android only issue. Working on macos and web as well

**Comment by ripls56** [comment]
Yeah, ran it on the emulator expectantly and it doesn't work

<img width="587" alt="image" src="https://github.com/Milad-Akarie/skeletonizer/assets/84716344/77c32666-c833-4dbe-924a-88be2b02c9fb">

**Comment by Milad-Akarie** [comment]
Hey @ripls56 please confirm the fix and close

**Comment by ripls56** [comment]
Yep, everything works now, thanks for fix
