### ISSUE TITLE
Support for nested Skeletons

### ISSUE THREAD

**Issue by Caesarovich** [Milad-Akarie/skeletonizer#33]
Hi,

I'm trying to make an `ExpansionTile` to work with `Skeletonizer`. For this I need to nest 2 Skeletonizers (One for the tile's main content, and one for the content loaded when it is expanded) but it appears that it is not supported as I get this error:

```dart
Skeletonizer widgets can not be nested directly, use Skeletonizer.zone as a parent for child Skeletonizers.
```

> Maybe I'm getting skill-issued here but not matter what I tried with a Skeletonizer.zone it didn't work.

So support to have multiple Skeletons would be really nice for Widgets like ExpansionTiles.

**Comment by Gagaved** [comment]
I also encountered this. Up to a certain version, it was possible to embed a Skeletonizer into a Skeletonizer, and this didn't cause an error. I might be wrong, but it seems that the issue appeared when Bone was added.

**Comment by Milad-Akarie** [comment]
@Caesarovich @Gagaved  nesting skeletonizes is now allowed in 1.2.0, please confirm and close

**Comment by SherlockHolmes2045** [comment]
Just tested @Milad-Akarie  works fine thank you for the update

**Comment by Caesarovich** [comment]
Nice job @Milad-Akarie 👍
