### ISSUE TITLE
Add Support for Animations in Container

### ISSUE THREAD

**Issue by Nicholasvp** [Milad-Akarie/skeletonizer#38]
Hi, it would be great if this package could support animations for the container. This feature would allow developers to create more dynamic and visually appealing interfaces. Currently, it's challenging to animate the container directly. Having this feature integrated would significantly enhance the package's functionality and usability.

Proposed Solution:
Consider integrating a way to animate the container, similar to how other animation widgets work in Flutter. This could involve:

Adding a parameter to enable animations.
Providing predefined animation styles or allowing custom animations.
Thank you for considering this feature request!

**Comment by Milad-Akarie** [comment]
@Nicholasvp what do you mean my animating the container?

**Comment by Milad-Akarie** [comment]
@Nicholasvp wrap your container with Skeleton.leaf
