### ISSUE TITLE
Skeleton not scrolling horizontally

### ISSUE THREAD

**Issue by MoyinShabi** [Milad-Akarie/skeletonizer#4]
Hi @Milad-Akarie, thank you for this great package! I recently came across it and I've been trying to learn how to best use it in my Flutter app. 

I need to ask please, is it a normal behaviour for the Skeletonizer widget to not be able to scroll through a list view horizontally? In the attached video, you can see just what I'm talking about. When I perform a hot restart on the app in order to see the Skeletonizer shimmer loading effect, I can't scroll through each horizontal list view unlike when the data from the server has loaded. Thank you in advance for your response.

Also, could you please give me some feedback regarding my use of the package in the example code below? Could I have gone about it in a much better way that you know of? I have definitely taken some time to go through the package documentation and the medium article provided but I could not really use any of the resources to fully understand how I could use it in my app. Though I did get the basic understanding of what I could achieve with the package from the docs, the code style and use of state management in the medium article were beyond my current skill level.

Finally, I need to ask, what do you suggest is the reason for the behaviour between `1:25-01:52` of the video? When the number of characters of the longer dummy text for the podcast name was reduced, it affected the way the skeleton of the artist name was rendered (kindly zoom into the video for a clearer view).

I definitely desire to understand fully how to use this awesome package so I can also talk about it with others and probably write an article of my own on a simple use case like my current one, to create more awareness.

Once again, thank you in advance for your time & response!
P.S I'm a beginner Flutter Dev; please pardon my many questions, sigh.
 

https://github.com/Milad-Akarie/skeletonizer/assets/21967002/3cf4bcb6-cfad-4b74-bd2e-0f2a885462eb

> `browse_category.dart`
```dart
import 'package:flutter/material.dart';
import 'package:skeletonizer/skeletonizer.dart';

import '../core/services/podcast_service.dart';

class BrowseCategory extends StatelessWidget {
  final String title;
  final String genre;

  const BrowseCategory({
    super.key,
    required this.title,
    this.genre = '',
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              title,
              style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
              ),
            ),
            TextButton(
              onPressed: () {},
              child: const Text('See All'),
            ),
          ],
        ),
        FutureBuilder(
          future: PodcastService().fetchPodcasts(genre: genre),
          builder: (context, snapshot) {
            if (snapshot.hasData) {
              return SizedBox(
                height: 230,
                child: ListView.separated(
                  separatorBuilder: (context, index) =>
                      const SizedBox(width: 10),
                  scrollDirection: Axis.horizontal,
                  itemCount: snapshot.data?.resultCount ?? 0,
                  itemBuilder: (context, index) {
                    final items = snapshot.data?.items;
                    final item = items?[index];
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        ClipRRect(
                          borderRadius: BorderRadius.circular(10),
                          child: Image.network(
                            item?.artworkUrl600 ?? '',
                            fit: BoxFit.fill,
                            height: 150,
                            width: 150,
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text((index + 1).toString()),
                        SizedBox(
                          width: 150,
                          child: Text(
                            item?.trackName ?? '',
                            style: const TextStyle(fontSize: 12),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                        SizedBox(
                          width: 150,
                          child: Text(
                            item?.artistName ?? '',
                            style: const TextStyle(
                              fontSize: 10,
                              color: Colors.grey,
                            ),
                            overflow: TextOverflow.ellipsis,
                          ),
                        )
                      ],
                    );
                  },
                ),
              );
            }
            if (snapshot.hasError) {
              return const Center(
                child: Text(
                    'Oops! Something went wrong. Please check your internet connection.'),
              );
            }
            return Skeletonizer(
              enabled: true,
              child: SizedBox(
                height: 230,
                child: ListView.separated(
                  separatorBuilder: (context, index) =>
                      const SizedBox(width: 10),
                  scrollDirection: Axis.horizontal,
                  itemCount: 20,
                  itemBuilder: (context, index) {
                    return Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        ClipRRect(
                          borderRadius: BorderRadius.circular(10),
                          child: Image.network(
                            'https://via.placeholder.com/600x600',
                            fit: BoxFit.fill,
                            height: 150,
                            width: 150,
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text((index + 1).toString()),
                        const SizedBox(
                          width: 150,
                          child: Text(
                            'Lorem ipsum dolor sit amet consechhj',
                            style: TextStyle(fontSize: 12),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                        const SizedBox(
                          width: 150,
                          child: Text(
                            'Lorem ipsum dolor',
                            style: TextStyle(
                              fontSize: 10,
                              color: Colors.grey,
                            ),
                            overflow: TextOverflow.ellipsis,
                          ),
                        )
                      ],
                    );
                  },
                ),
              ),
            );
          },
        ),
      ],
    );
  }
}

```

> `podcast_service.dart`
```dart
import 'package:podcast_search/podcast_search.dart';

class PodcastService {
  Future<SearchResult> fetchPodcasts({String genre = ''}) async {
    final search = Search();
    final results = await search.charts(
      country: Country.nigeria,
      limit: 20,
      genre: genre,
    );
    return results;
  }
}

```

**Comment by Milad-Akarie** [comment]
Hey, @MoyinShabi first of all, welcome to Flutter,  secondly, yes it is intended in the current version for skeletonizer to ignore pointers ( that's any kind of interaction, tap, scroll ...etc).
I can add a flag to let users enable/disable interactions, but then even tap events might occur and no one would want their skeleton loaders to be tappable.

The right way to go about this is to skeletonize the items but not the ListView so in your example you would wrap the `Culumn` widget with `Skeletonizer` widget but that would be a bit expensive in the current version of skeletonizer.

The good news is that I've been working on redesigning the internal API to be much preferment and the results are perfect, it should be ready in two to three days.

**Comment by MoyinShabi** [comment]
That’s great to hear! I look forward to the new version. 

How about the way I went about using the Skeletonizer widget in my code example above please? Is it fine that I just copied the code of the actual UI to be rendered when the data has loaded and replaced the real data with dummy data? Is this approach expensive in any way also?

**Comment by Milad-Akarie** [comment]
@MoyinShabi What you have works but it can be done better, one of the main goals of skeletonizer is not having to keep your skeleton view in sync with the actual view if you ever change it, so it's better to extract your list item as a separate widget which's a recommended flutter approach in the first place, 

then you can use it like so 
if data is available 
`MyListItem(image: item.image, title: item.title, subtitle: item.subtitle)`

when loading..
`Skeletonizer(child: MyListItem(image:'', title: 'Fake title', subtitle: 'Fake subtitle))`
this way when you change the layout of MyListItem you guarantee that you skeleton view is also using the same layout.

or better yet do this for the entire list
here's an article that explains it in detail
https://milad-akarie.medium.com/flutter-skeleton-loader-using-skeletonizer-13d410dc4ac7

**Comment by Milad-Akarie** [comment]
Hey @MoyinShabi  with the new version you can set ignore pointers to false `Skeletonizer(ignorePointers: false)` so that taps, scroll events etc will work while skeletonizer is enabled, to disable pointer events for specific widgets ( so no tap events are received while skeletonizer is enabled), use `Skeleton.ignorePointer` annotation widget

**Comment by MoyinShabi** [comment]
Hi @Milad-Akarie, thanks a lot for the helpful feedback given earlier.

Also, well done on the new version and thanks for the update!
