### ISSUE TITLE
How do I set the color of the animation?

### ISSUE THREAD

**Issue by sed1ka** [Milad-Akarie/skeletonizer#6]
This isnt issue, but I cant find to how to change the color of animation.
If this feature doesn't exist yet, maybe it can be used as a feature request. Thanks

**Comment by Milad-Akarie** [comment]
Hey @sed1ka you can customize the animation effect and its properties like follows

```dart
Skeletonizer(
    enabled: _enabled,
    effect: ShimmerEffect(
      baseColor:  myBaseColor,
      highlightColor:  myHighlightColor,
    ),
    child:  ...
  )
```
or if you want to create your own gradient
```dart
Skeletonizer(
    enabled: _enabled,
    effect: ShimmerEffect.raw(
      colors: [],
      stops: []
    ), 
    child: ...
)
```
