### ISSUE TITLE
Is there a known issue where skeletonizer would render the fake data instead of the loader?

### ISSUE THREAD

**Issue by haidarmehsen** [Milad-Akarie/skeletonizer#7]
Hello Milad, first of all thank you alot for this awesome package.

I am using it in release mode and one time I faced the problem of skeletonizer rendering the fake data instead of the loader, is there a known case/device/OS version... which has this problem?

I know I should mention reproducible steps, but unfortunately I am not yet able to reproduce it.

Thanks again!

**Comment by Milad-Akarie** [comment]
Hey @haidarmehsen nope, This's the first report, but I suspected something after reading your issue which is the layer I'm painting on might be cashed or using a cashed context, so I changed to using my own layer in version 0.6.0.

if you have any further info please let me know.

**Comment by haidarmehsen** [comment]
@Milad-Akarie thanks for your response, I am still using version 0.3.0.

So do you not recommend using this plugin at this time in production?

**Comment by Milad-Akarie** [comment]
@haidarmehsen 0.4.0+ uses an entirely different implementation. So your reported issue is not valid I guess. 
after version 0.4.0 the internal API is stable and can be used in Production, I personally use it in my production Apps.

**Comment by haidarmehsen** [comment]
@Milad-Akarie Thanks again, I will try to upgrade and give you more info if I face this again
