### ISSUE TITLE
Weird behaviour when using a BackdropFilter

### ISSUE THREAD

**Issue by rienkkk** [Milad-Akarie/skeletonizer#9]
Love the package!

A backdrop filter inside a skeletonizer blurs the whole widget instead of only the background. Example picture:

<img src="https://github.com/Milad-Akarie/skeletonizer/assets/57758628/54cb8427-8ab4-4562-959b-2201e774ab89" width="200" />

It only blurs the whole widget when the skeletonizer is enabled, when disabled everything works as expected.

Minimal sample code that demonstrates the issue:

```dart
Skeletonizer(
  child: BackdropFilter(
    filter: ImageFilter.blur(sigmaX: 10, sigmaY: 10),
    child: Container(
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.4),
      ),
      width: 100,
      height: 100,
      child: Text(
        'test test test test',
      ),
    ),
  ),
);
```

My current work around is to change the sigmaX/Y blur to 0 when the skeletonizer is enabled.

**Comment by Milad-Akarie** [comment]
@rienkkk I've been working on some fixes and just published a new release, I tried your code sample and it works just fine, can you confirm if you still have this issue with release 0.7.0?

**Comment by rienkkk** [comment]
0.7.0 fixed it! Thanks
